name: 'test-app'
description: 'Test a Shiny application or document with shinytest2'
author: 'Barret Schloerke'
inputs:
  app-dir:
    description: 'Directory of Shiny application (or Shiny-based document) to test'
    default: '.'
    required: false
  upload-snapshots:
    description: 'Whether to upload all testthat snapshots as an artifact.'
    default: false
    required: false
runs:
  using: "composite"
  steps:
    - name: R version
      shell: Rscript {0}
      id: st2-r-version
      run: |
        ## --------------------------------------------------------------------
        v <- paste0(version$major, ".", version$minor)
        cat("version=", v, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)

    - name: Test app
      shell: Rscript {0}
      run: |
        ## --------------------------------------------------------------------
        options(crayon.enabled = TRUE)
        shinytest2::test_app("${{ inputs.app-dir }}")

    - name: Show testthat output
      if: always()
      run: |
        ## --------------------------------------------------------------------
        echo ::group::Show testthat output
        find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        echo ::endgroup::
      shell: bash
      working-directory: ${{ inputs.app-dir }}

    - name: Upload snapshots
      if: inputs.upload-snapshots != 'false'
      uses: actions/upload-artifact@main
      with:
        name: ${{ runner.os }}-r${{ steps.st2-r-version.outputs.version }}-testthat-snapshots
        path: ${{ inputs.app-dir }}/tests*/testthat/_snaps
        if-no-files-found: ignore
