on:
  push:
    paths:
      - '.github/workflows/render-readme-pak.yaml'
      - 'README.Rmd'

name: Render README.Rmd

jobs:
  render:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          needs: readme
          extra-packages: rmarkdown

      - name: Render README
        shell: Rscript {0}
        run: |
          rmarkdown::render("README.Rmd")

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
