testthat_expect_snapshot_output <- function( # nolint
  private,
  x,
  cran = FALSE
  # , variant = NULL
) {
  testthat::expect_snapshot_output(
    x,
    cran = cran,
    variant = private$variant
  )
}
testthat_expect_snapshot_file <- function(
  private,
  file,
  name = fs::path_file(file),
  cran = FALSE,
  compare = testthat::compare_file_binary
  # , variant = NULL
) {
  # Add name prefix to saved snapshot file
  name <-
    if (is.null(private$name)) {
      name
    } else {
      paste0(private$name, "-", name)
    }

  testthat::expect_snapshot_file(
    file,
    name = name,
    cran = cran,
    compare = compare,
    variant = private$variant
  )
}



#' Expect a shinytest2 snapshot
#'
#'
#' @param app A [ShinyDriver2] object.
#' @param ... Must be empty. Allows for parameter expansion.
#' @param name The prefix name to be used for the snapshot. By default, this uses the name supplied to `app` on initialization.
#' @param items Elements to only be included in the snapshot. If supplied, can contain `inputs`, `output`, and `export`. Each value of `items` can either be `TRUE` (for all values) or a character list of names to use.
#' @param screenshot A boolean indicating whether to take a screenshot.
#' @inheritParams testthat::expect_snapshot_file
#' @export
app_expect_appshot <- function(
  app,
  ...,
  name = NULL,
  items = NULL,
  screenshot = NULL,
  # variant = NULL,
  cran = FALSE
) {
  app$expectAppshot(
    ...,
    name = name,
    items = items,
    screenshot = screenshot,
    cran = cran
    # , variant = variant
  )

}



#' @description
#' Internal method. Generally, you should not call this function
#' yourself; it will be generated by `recordTest()` as needed.
#' @param items Elements to include in snapshot
#' @param filename Filename to use
#' @param screenshot Take a screenshot? Overrides value set by
#'   `$snapshotInit()`
#' @include shiny-driver.R
ShinyDriver2$set("public", "expectAppshot", function(
  ...,
  name = NULL,
  items = NULL,
  screenshot = NULL,
  error = FALSE,
  cran = FALSE
) {
  testthat::expect_s3_class(self, "ShinyDriver2")
  ellipsis::check_dots_empty()

  snapshot_info <- sd2_snapshot(self, private, items = items, name = name, screenshot = screenshot)

  # compare json
  testthat_expect_snapshot_file(
    private,
    snapshot_info$json_path,
    cran = cran,
    compare = testthat::compare_file_text
    # , variant = variant
  )

  # compare screenshot
  if (!is.null(snapshot_info$screenshot_path)) {
    testthat_expect_snapshot_file(
      private,
      snapshot_info$screenshot_path,
      cran = cran,
      compare = testthat::compare_file_binary
      # , variant = variant
    )
  }

  invisible(self)
})
