#' @description
#' Internal method. Generally, you should not call this function
#' yourself; it will be generated by `record_test()` as needed.
#' @param items Elements to include in snapshot
#' @param filename Filename to use
#' @param screenshot Take a screenshot? Overrides value set by
#'   `$snapshotInit()`
#' @include shiny-driver.R
#' @importFrom rlang !!!
ShinyDriver2$set("public", "expectSnapshotJS", function(
  script,
  ...,
  post_script = NULL,
  cran = FALSE
) {
  ellipsis::check_dots_unnamed()
  arguments <- list2(...)
  testthat::expect_s3_class(self, "ShinyDriver2")

  result <- self$execute_script(script, !!!arguments)

  if (is.function(post_script)) {
    checkmate::assert_integer(length(formals(post_script)), lower = 1)
    result <- post_script(result)
  }

  testthat_expect_snapshot_output(
    private,
    result,
    cran = cran
  )
})



#' Expect snapshot of JS script output
#'
#' This is a building block function that should be called by other functions.
#' For example, [`app_expect_html()`] and [`app_expect_text()`] are thin wrappers around this function.
#'
#' @param app A [ShinyDriver2] object.
#' @param script A string containing the JS script to be executed.
#' @param ... Must be empty. Allows for parameter expansion.
#' @param arguments A list of arguments to be passed to the script.
#' @param post_script A function to be called on the result of the script before taking the snapshot.
#'   [`app_expect_html()`] and [`app_expect_text()`] both use [`unlist()`].
#' @inheritParams testthat::expect_snapshot_output
#' @export
app_expect_js <- function(
  app,
  script,
  ..., # Ignored
  arguments = list2(), # TODO-barret-question; or  make this the `...`?
  # TODO-barret-answer; Use `arguments` be consistent throughout the package
  post_script = NULL,
  # variant = NULL,
  cran = FALSE
) {
  ellipsis::check_dots_empty()
  app$expectSnapshotJS(
    script = script, !!!arguments,
    # variant = variant,
    post_script = post_script,
    cran = cran
  )
}

#' Expect App DOM or text snapshot
#'
#' These methods will find all matching elements and extract their respective values.
#' These values will then be stored as a snapshot.
#' The snapshot `variant` will be extracted from the `app` object directly.
#'
#' @param app A [ShinyDriver2] object.
#' @param selector A DOM selector to be passed into jQuery
#' @param ... Must be empty. Allows for parameter expansion.
#' @inheritParams testthat::expect_snapshot_output
#' @describeIn app_expect_html This method will extract the text value of all matching elements via `tag.textContent`.
#'   This method is more robust to internal package change as only the text values will be return.
#'   When possible, use `app_expect_text()` over `app_expect_html()` to allow package authors room to change.
#' @export
app_expect_text <- function(
  app,
  selector,
  ...,
  # variant = NULL,
  cran = FALSE
) {
  ellipsis::check_dots_empty()
  app_expect_js(
    app,
    script = paste0("return Array.from(document.querySelectorAll(\"", selector, "\")).map(function(item, i) { return item.textContent; });"),
    # variant = variant,
    post_script = unlist,
    cran = cran
  )
}
#' @describeIn app_expect_html This method will extract the relevant DOM structure of all matching elements.
#'   This method is great for testing the full DOM structure of particular HTML elements.
#'   It is recommended to only use this method on DOM elements that you have full control over.
#'   This will help avoid false-positives when underlying packages may update.
#' @param outer_html If `TRUE`, the full DOM structure will be returned (`tag.outerHTML`).
#'   If `FALSE`, the full DOM structure of the child elements will be returned (`tag.innerHTML`).
#' @export
app_expect_html <- function(
  app,
  selector,
  ...,
  # variant = NULL,
  outer_html = FALSE,
  cran = FALSE
) {
  ellipsis::check_dots_empty()
  html_code <-
    if (isTRUE(outer_html)) {
      "item.outerHTML"
    } else {
      "item.innerHTML"
    }
  app_expect_js(
    app,
    script = paste0("return Array.from(document.querySelectorAll(\"", selector, "\")).map(function(item, i) { return ", html_code, "; });"),
    # variant = variant,
    post_script = unlist,
    cran = cran
  )
}
