#' @description
#' Internal method. Generally, you should not call this function
#' yourself; it will be generated by `record_test()` as needed.
#' @param items Elements to include in snapshot
#' @param filename Filename to use
#' @param screenshot Take a screenshot? Overrides value set by
#'   `$snapshotInit()`
#' @include shiny-driver.R
# TODO-barret-rename; `expect_script`?
ShinyDriver2$set("public", "expect_js", function(
  script,
  ...,
  post_fn = NULL,
  cran = FALSE
) {
  ellipsis::check_dots_unnamed()
  arguments <- list2(...)
  testthat::expect_s3_class(self, "ShinyDriver2")

  result <- self$execute_script(script, ...)

  if (is.function(post_fn)) {
    checkmate::assert_integer(length(formals(post_fn)), lower = 1)
    result <- post_fn(result)
  }

  testthat_expect_snapshot_output(
    private,
    result,
    cran = cran
  )
})



#' Expect snapshot of JS script output
#'
#' This is a building block function that should be called by other functions.
#' For example, [`app_expect_html()`] and [`app_expect_text()`] are thin wrappers around this function.
#'
#' @param app A [ShinyDriver2] object.
#' @param script A string containing the JS script to be executed.
#' @param ... Must be empty. Allows for parameter expansion.
#' @param arguments A list of arguments to be passed to the script.
#' @param post_fn A function to be called on the result of the script before taking the snapshot.
#'   [`app_expect_html()`] and [`app_expect_text()`] both use [`unlist()`].
#' @inheritParams testthat::expect_snapshot_output
#' @export
#' @importFrom rlang !!!
app_expect_js <- function(
  app,
  script,
  ..., # Ignored
  arguments = list2(), # TODO-barret-question; or  make this the `...`?
  # TODO-barret-consistency; `...` or `arguments`!
  # TODO-barret-answer; Use `arguments` or be consistent throughout the package
  post_fn = NULL,
  cran = FALSE
) {
  ellipsis::check_dots_empty()
  app$expect_js(
    script = script, !!!arguments,
    post_fn = post_fn,
    cran = cran
  )
}



#' @description
#' @param app A [ShinyDriver2] object.
#' @param selector A DOM selector to be passed into jQuery
#' @include shiny-driver.R
ShinyDriver2$set("public", "expect_text", function(
  selector,
  ...,
  cran = FALSE
) {
  ellipsis::check_dots_empty()
  app_expect_js(
    app,
    script = paste0("return Array.from(document.querySelectorAll(\"", selector, "\")).map(function(item, i) { return item.textContent; });"),
    post_fn = unlist,
    cran = cran
  )

  invisible(self)
})

#' Expect App DOM or text snapshot
#'
#' These methods will find all matching elements and extract their respective values.
#' These values will then be stored as a snapshot.
#' The snapshot `variant` will be extracted from the `app` object directly.
#'
#' @param app A [ShinyDriver2] object.
#' @param selector A DOM selector to be passed into jQuery
#' @param ... Must be empty. Allows for parameter expansion.
#' @inheritParams testthat::expect_snapshot_output
#' @describeIn app_expect_html This method will extract the text value of all matching elements via `tag.textContent`.
#'   This method is more robust to internal package change as only the text values will be return.
#'   When possible, use `app_expect_text()` over `app_expect_html()` to allow package authors room to change.
#' @export
app_expect_text <- function(
  app,
  selector,
  ...,
  cran = FALSE
) {
  app$expect_text(
    selector = selector,
    cran = cran,
    post_fn = NULL,
    ...
  )
}





#' @description
#' @param app A [ShinyDriver2] object.
#' @param selector A DOM selector to be passed into jQuery
#' @param outer_html If `TRUE`, the full DOM structure will be returned (`tag.outerHTML`).
#'   If `FALSE`, the full DOM structure of the child elements will be returned (`tag.innerHTML`).
#' @include shiny-driver.R
ShinyDriver2$set("public", "expect_html", function(
  selector,
  ...,
  outer_html = FALSE,
  cran = FALSE
) {
  ellipsis::check_dots_empty()

  html_code <-
    if (isTRUE(outer_html)) {
      "item.outerHTML"
    } else {
      "item.innerHTML"
    }

  app_expect_js(
    app,
    script = paste0("return Array.from(document.querySelectorAll(\"", selector, "\")).map(function(item, i) { return ", html_code, "; });"),
    post_fn = unlist,
    cran = cran
  )

  invisible(self)
})

#' @describeIn app_expect_html This method will extract the relevant DOM structure of all matching elements.
#'   This method is great for testing the full DOM structure of particular HTML elements.
#'   It is recommended to only use this method on DOM elements that you have full control over.
#'   This will help avoid false-positives when underlying packages may update.
#' @param outer_html If `TRUE`, the full DOM structure will be returned (`tag.outerHTML`).
#'   If `FALSE`, the full DOM structure of the child elements will be returned (`tag.innerHTML`).
#' @export
app_expect_html <- function(
  app,
  selector,
  ...,
  outer_html = FALSE,
  cran = FALSE
) {
  app$expect_html(
    selector = selector,
    outer_html = outer_html,
    cran = cran,
    ...
  )
}
