#' @description
#' Internal method. Generally, you should not call this function
#' yourself; it will be generated by `recordTest()` as needed.
#' @param items Elements to include in snapshot
#' @param filename Filename to use
#' @param screenshot Take a screenshot? Overrides value set by
#'   `$snapshotInit()`
#' @include shiny-driver.R
#' @importFrom rlang !!!
# TODO-barret; Is this method needed to be public? Similar to `app$expectAppshot()`
ShinyDriver2$set("public", "expectSnapshotJS", function(
  script,
  ...,
  post_script = NULL,
  cran = FALSE
) {
  ellipsis::check_dots_unnamed()
  arguments <- list2(...)
  testthat::expect_s3_class(self, "ShinyDriver2")

  result <- self$executeScript(script, !!!arguments)

  if (is.function(post_script)) {
    checkmate::assert_integer(length(formals(post_script)), lower = 1)
    result <- post_script(result)
  }

  testthat_expect_snapshot_output(
    private,
    result,
    cran = cran
  )
})


# ShinyDriver2

#' Expect snapshot of JS script output
#'
#' This is a building block function that should be called by other functions.
#' For example, [`expect_snapshot_app_dom()`] and [`expect_snapshot_app_text()`] are thin wrappers around this function.
#'
#' @param app A [ShinyDriver2] object.
#' @param script A string containing the JS script to be executed.
#' @param ... Must be empty. Allows for parameter expansion.
#' @param arguments A list of arguments to be passed to the script.
#' @param post_script A function to be called on the result of the script before taking the snapshot.
#'   [`expect_snapshot_app_dom()`] and [`expect_snapshot_app_text()`] both use [`unlist()`].
#' @inheritParams testthat::expect_snapshot_output
#' @export
# TODO-barret; Rename to `app_expect_js()`
expect_snapshot_app_js <- function(
  app,
  script,
  ...,
  arguments = list2(), # TODO-barret; or  make this the `...`?
  post_script = NULL,
  # variant = NULL,
  cran = FALSE
) {
  ellipsis::check_dots_empty()
  app$expectSnapshotJS(
    script = script, !!!arguments,
    # variant = variant,
    post_script = post_script,
    cran = cran
  )
}

#' Expect App DOM or text snapshot
#'
#' These methods will find all matching elements and extract their respective values.
#' These values will then be stored as a snapshot.
#' The snapshot `variant` will be extracted from the `app` object directly.
#'
#' @param app A [ShinyDriver2] object.
#' @param selector A DOM selector to be passed into jQuery
#' @param ... Must be empty. Allows for parameter expansion.
#' @inheritParams testthat::expect_snapshot_output
#' @describeIn expect_snapshot_app_dom This method will extract the text value of all matching elements via `$(el).text()`.
#'   This method is more robust to internal package change as only the text values will be return.
#'   When possible, use `expect_snapshot_app_text()` over `expect_snapshot_app_dom()` to allow package authors room to change.
#' @export
# TODO-barret; rename to `app_expect_text()`
expect_snapshot_app_text <- function(
  app,
  selector,
  ...,
  # variant = NULL,
  cran = FALSE
) {
  ellipsis::check_dots_empty()
  expect_snapshot_app_js(
    app,
    script = paste0("return $(\"", selector, "\").map(function(i, item) { return $(item).text() }).get();"),
    # variant = variant,
    post_script = unlist,
    cran = cran
  )
}
#' @describeIn expect_snapshot_app_dom This method will extract the relevant DOM structure of all matching elements.
#'   This method is great for testing the full DOM structure of particular HTML elements.
#'   It is recommended to only use this method on DOM elements that you have full control over.
#'   This will help avoid false-positives when underlying packages may update.
#' @param outer_html If `TRUE`, the full DOM structure will be returned (`el.outerHTML`).
#'   If `FALSE`, the full DOM structure of the child elements will be returned (`$(el).html()`).
#' @export
# TODO-barret; rename to `app_expect_dom()`
expect_snapshot_app_dom <- function(
  app,
  selector,
  ...,
  # variant = NULL,
  outer_html = FALSE,
  cran = FALSE
) {
  ellipsis::check_dots_empty()
  html_code <-
    if (isTRUE(outer_html)) {
      "item.outerHTML"
    } else {
      "$(item).html()"
    }
  expect_snapshot_app_js(
    app,
    script = paste0("return $(\"", selector, "\").map(function(i, item) { return ", html_code, "; }).get();"),
    # variant = variant,
    post_script = unlist,
    cran = cran
  )
}
