# Generated by cpp11: do not edit by hand

image_diff_convolution_max_value <- function(diff_matrix, kernel_size, threshold) {
  .Call(`_shinytest2_image_diff_convolution_max_value`, diff_matrix, kernel_size, threshold)
}
