# Generated by cpp11: do not edit by hand

image_diff_breaks_threshold <- function(diff_matrix, kernal_size, threshold) {
  .Call(`_shinytest2_image_diff_breaks_threshold`, diff_matrix, kernal_size, threshold)
}
