on:
  push:
    branches: [main, rc-**]
  pull_request:
    branches: [main]

name: R-CMD-check

jobs:
  R-CMD-check:
    uses: schloerke/shiny-actions/.github/workflows/call-r-cmd-check.yaml@main
  pkgdown:
    uses: schloerke/shiny-actions/.github/workflows/call-r-pkgdown.yaml@main
