# Workflow derived from https://github.com/rstudio/shiny-workflows
#
# NOTE: This Shiny team GHA workflow is overkill for most R packages.
# For most R packages it is better to use https://github.com/r-lib/actions
on:
  push:
    branches: [main, rc-**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 8 * * 1' # every monday

name: Package checks

jobs:
  website:
    uses: rstudio/shiny-workflows/.github/workflows/website.yaml@v1
  routine:
    uses: rstudio/shiny-workflows/.github/workflows/routine.yaml@v1
  R-CMD-check:
    uses: rstudio/shiny-workflows/.github/workflows/R-CMD-check.yaml@v1
    with:
      cache-version: "4"
  vanilla-example:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}

          # - {os: windows-latest, r: 'release'}
          # # Use 3.6 to trigger usage of RTools35
          # - {os: windows-latest, r: '3.6'}

          # # Use older ubuntu to maximise backward compatibility
          # - {os: ubuntu-18.04,   r: 'devel', http-user-agent: 'release'}
          # - {os: ubuntu-18.04,   r: 'release'}
          # - {os: ubuntu-18.04,   r: 'oldrel-1'}
          # - {os: ubuntu-18.04,   r: 'oldrel-2'}
          # - {os: ubuntu-18.04,   r: 'oldrel-3'}
          # - {os: ubuntu-18.04,   r: 'oldrel-4'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          cache-version: "vanilla"

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
